function Hd = designed_filter
%DESIGNED_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 15-Apr-2025 00:56:35

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 44.1;  % Sampling Frequency

N    = 15;       % Order
Fc   = 3.4;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
