function Hd = designed_filter
%DESIGNED_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 17-Apr-2025 23:48:38

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in MHz.
Fs = 100;  % Sampling Frequency

N    = 15;       % Order
Fc   = 10;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);
%fvtool(Hd)
% [EOF]
